### ISSUE TITLE
missing contain in newrelic class

### ISSUE THREAD

**Issue by c4m4** [claranet/puppet-newrelic#17]
missing contain in newrelic class for the included classes

**Comment by craigwatson** [comment]
Hi,

Thanks for raising this issue, however can you provide more detail on the problem?

As far as I’m aware, the module doesn’t need `contain` statements for its subclasses, and I haven’t seen any documentation that suggests a best practice for modules declaring their subclasses. 

Thanks,
Craig

**Comment by c4m4** [comment]
thanks for your reply, let me explain my problem, I have a role::phpapplication and profiles

```
class role::phpapplication {
  contain '::profiles::php' #this class install php
  contain '::profies::newrelic' #this class use newrelic class

  Class['profiles::php'] ->
    Class['profies::newrelic']
}
```
class profiles::newrelic {
  contain '::newrelic'
}

in hiera I have:

```
newrelic::license_key: 'XXKXKXKX'
newrelic::enable_server: false
newrelic::enable_infra: false
newrelic::enable_php_agent: true

The problem is newrelic::agent::php begin applied before php

https://puppet.com/blog/class-containment-puppet




```
